[gormDB]
db-type = "mysql"
ip = "192.168.3.61"
port = "3306"
username = "root"
password = "admin"
db-name = "swa-demo"
config = "charset=utf8mb4&parseTime=True&loc=Local"
prefix = ""
singular = "false"
engine = ""
max-idle-conns = "10"
max-open-conns = "100"
log-mode = "error"
log-zap = "false"

[jwt]
signing-key = "30e074ea-8435-4c69-bb09-d6f1d8ad85a6"
expires-time = "7d"
buffer-time = "3d"
issuer = "qmPlus"

[captcha]
key-long = 6
img-width = 240
img-height = 80
open-captcha = 0
open-captcha-timeout = 3600

[redis]
db = 0
addr = "127.0.0.1=6379"
password = ""

[system]
env = "release"
addr = "9003"
db-type = "mysql"
oss-type = "local"
use-multipoint = "false"
use-redis = "false"
ip-limit-count = 15000
ip-limit-time = 3600
router-prefix = ""

[local]
path = "file_server/upload"
store-path = "file_server/upload/files"